-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 19:52:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BAVI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BAVI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BAVI` DEFAULT CHARACTER SET utf8 ;
USE `BAVI` ;

-- -----------------------------------------------------
-- Table `BAVI`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Member` (
  `MEMBER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `BIRTHDATE` DATE NULL,
  `PHONE` INT NULL,
  `EMAIL` VARCHAR(200) NULL,
  `ADRESS_ID` INT NOT NULL,
  `DATE_JOINED` DATETIME NOT NULL,
  `STREET` VARCHAR(250) NOT NULL,
  `ZIP_CODE` INT NOT NULL,
  `CITY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`MEMBER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Composer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Composer` (
  `COMPOSER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(200) NOT NULL,
  `SURNAME` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`COMPOSER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Genre` (
  `GENRE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`GENRE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Publisher` (
  `PUBLISHER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PUBLISHER_ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Song` (
  `SONG_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `URL` VARCHAR(250) NOT NULL,
  `PUBLISHER_ID` INT NOT NULL,
  `GENRE_ID` INT NOT NULL,
  `COMPOSER_ID` INT NOT NULL,
  `PRICE` DOUBLE NULL,
  `DATE_CREATED` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  PRIMARY KEY (`SONG_ID`),
  UNIQUE INDEX `idSong_UNIQUE` (`SONG_ID` ASC) VISIBLE,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE,
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC) VISIBLE,
  INDEX `fk_Song_Publisher1_idx` (`PUBLISHER_ID` ASC) VISIBLE,
  INDEX `fk_Song_Genre1_idx` (`GENRE_ID` ASC) VISIBLE,
  INDEX `fk_Song_Composer1_idx` (`COMPOSER_ID` ASC) VISIBLE,
  INDEX `fk_Song_Member1_idx` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Song_Publisher1`
    FOREIGN KEY (`PUBLISHER_ID`)
    REFERENCES `BAVI`.`Publisher` (`PUBLISHER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Genre1`
    FOREIGN KEY (`GENRE_ID`)
    REFERENCES `BAVI`.`Genre` (`GENRE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Composer1`
    FOREIGN KEY (`COMPOSER_ID`)
    REFERENCES `BAVI`.`Composer` (`COMPOSER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Member1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `BAVI`.`Member` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Function` (
  `FUNCTION_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FUNCTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`Instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`Instrument` (
  `INSTRUMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`INSTRUMENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`MemberFunction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`MemberFunction` (
  `MEMBER_ID` INT NOT NULL,
  `FUNCTION_ID` INT NOT NULL,
  PRIMARY KEY (`MEMBER_ID`, `FUNCTION_ID`),
  INDEX `fk_Member_has_Function_Function1_idx` (`FUNCTION_ID` ASC) VISIBLE,
  INDEX `fk_Member_has_Function_Member1_idx` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Member_has_Function_Member1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `BAVI`.`Member` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has_Function_Function1`
    FOREIGN KEY (`FUNCTION_ID`)
    REFERENCES `BAVI`.`Function` (`FUNCTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAVI`.`MemberInstrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BAVI`.`MemberInstrument` (
  `MEMBER_ID` INT NOT NULL,
  `INSTRUMENT_ID` INT NOT NULL,
  PRIMARY KEY (`MEMBER_ID`, `INSTRUMENT_ID`),
  INDEX `fk_Member_has_Instrument_Instrument1_idx` (`INSTRUMENT_ID` ASC) VISIBLE,
  INDEX `fk_Member_has_Instrument_Member1_idx` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Member_has_Instrument_Member1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `BAVI`.`Member` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has_Instrument_Instrument1`
    FOREIGN KEY (`INSTRUMENT_ID`)
    REFERENCES `BAVI`.`Instrument` (`INSTRUMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
