-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 18:35:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Function` (
  `FUNCTION_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`FUNCTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instrument` (
  `INSTRUMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`INSTRUMENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `MEMBER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(250) NOT NULL,
  `SURNAME` VARCHAR(250) NOT NULL,
  `BIRTHDATE` DATE NULL,
  `PHONE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(200) NULL,
  `HOUSE_NUMBER` INT NULL,
  `DATE_JOINED` DATETIME NOT NULL,
  `FUNCTION_ID` INT NOT NULL,
  `INSTRUMENT_ID` INT NOT NULL,
  `STREET` VARCHAR(250) NULL,
  `ZIP_CODE` INT NULL,
  `CITY` VARCHAR(250) NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`MEMBER_ID`),
  INDEX `fk_Member_Function1_idx` (`FUNCTION_ID` ASC) VISIBLE,
  INDEX `fk_Member_Instrument1_idx` (`INSTRUMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Member_Function1`
    FOREIGN KEY (`FUNCTION_ID`)
    REFERENCES `mydb`.`Function` (`FUNCTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_Instrument1`
    FOREIGN KEY (`INSTRUMENT_ID`)
    REFERENCES `mydb`.`Instrument` (`INSTRUMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composer` (
  `COMPOSER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(250) NOT NULL,
  `SURNAME` VARCHAR(250) NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`COMPOSER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `GENRE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`GENRE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publisher` (
  `PUBLISHER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`PUBLISHER_ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Song` (
  `SONG_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `URL` VARCHAR(250) NULL,
  `PUBLISHER_ID` INT NOT NULL,
  `GENRE_ID` INT NOT NULL,
  `COMPOSER_ID` INT NOT NULL,
  `PRICE` DOUBLE NULL,
  `DATE_CREATED` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(250) NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  PRIMARY KEY (`SONG_ID`),
  UNIQUE INDEX `idSong_UNIQUE` (`SONG_ID` ASC) VISIBLE,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE,
  INDEX `fk_Song_Publisher1_idx` (`PUBLISHER_ID` ASC) VISIBLE,
  INDEX `fk_Song_Genre1_idx` (`GENRE_ID` ASC) VISIBLE,
  INDEX `fk_Song_Composer1_idx` (`COMPOSER_ID` ASC) VISIBLE,
  INDEX `fk_Song_Member1_idx` (`MEMBER_ID` ASC) VISIBLE,
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC) VISIBLE,
  CONSTRAINT `fk_Song_Publisher1`
    FOREIGN KEY (`PUBLISHER_ID`)
    REFERENCES `mydb`.`Publisher` (`PUBLISHER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Genre1`
    FOREIGN KEY (`GENRE_ID`)
    REFERENCES `mydb`.`Genre` (`GENRE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Composer1`
    FOREIGN KEY (`COMPOSER_ID`)
    REFERENCES `mydb`.`Composer` (`COMPOSER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_Member1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `mydb`.`Member` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
