version: '3'

services:


  backend:
    image: maven:3.9.6-amazoncorretto-21
    container_name: bavi_server
    entrypoint: sh -c "cd /app  && mvn clean package spring-boot:repackage && java -jar /app/target/bavi-1.0.0.jar"
    volumes:
      - ../:/app
    #ports:
     # - "8082:8082"
    depends_on:
      - mysql
      - minio
    restart: always
    networks:
      - backnet
      - frontnet
    expose:
      - 8082
    

  minio:
    image: minio/minio:latest
    container_name: minio_server
    #ports:
     # - "9000:9000"
    #- "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - backnet
    expose:
      - 9000

  mysql:
    image: mysql:latest
    container_name: mysql_server
    #ports:
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BAVI
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - backnet
    expose:
      - 3306

volumes:
  minio_data:
    driver: local

networks:
  backnet:
  frontnet:
